name: dnbapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.18.1"

dependencies:
  flutter:
    sdk: flutter

  # CORE PACKAGE
  get_it: ^5.0.3
  equatable: ^1.2.5
  flutter_hooks: ^0.15.0
  get: ^3.24.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  better_player: ^0.0.46


  # Service 
  flutter_facebook_auth: ^2.0.0+1
  google_maps_flutter: ^1.0.3
  just_audio: ^0.6.5
  firebase_storage: ^5.2.0
  image_picker: ^0.6.7+21
  video_player: ^1.0.1
  flutter_typeahead: ^2.0.0

  # UI
  modal_bottom_sheet: ^1.0.0+1
  convex_bottom_bar: ^2.6.0
  bubble_timeline: ^1.0.5
  user_profile_avatar: ^0.0.9
  linked_scroll_widgets: ^0.1.0
  flutter_neumorphic: ^3.0.3
  sliver_fab: ^1.0.0
  auto_animated: ^2.1.0
  animated_drawer: ^0.0.4
  liquid_swipe: ^1.5.0
  lottie: ^0.7.0+1
  sleek_circular_slider: ^1.2.0+web
  wave: ^0.1.0
  flashy_tab_bar: ^0.0.3
  animations: ^1.1.2
  step_progress_indicator: ^0.2.5+8
  flutter_swiper: ^1.1.6

  evolum_package:
    git:
      url: https://github.com/EvolumOU/evolum_package

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.1.1
  json_serializable: ^3.5.0
  build_runner: ^1.10.0
  copy_with_extension: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/badge/
    - assets/fonts/
    - assets/lottie/
    - assets/lottie/background/
    - assets/map/
